[package]
name = "mp3_mover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id3 = "1.8.0"
tempfile = "3.8.0"
glob = "0.3.1"
log = "0.4.20"
env_logger = "0.10.0"
